Realizando ajustes no yaml

diff --git a/github/workflows/01-building-blocks.yaml b/github/workflows/01-building-blocks.yaml
--- a/github/workflows/01-building-blocks.yaml
+++ b/github/workflows/01-building-blocks.yaml
@@ -1,19 +1,20 @@
 name: 01 - Building Blocks
+
 on: push
 
 jobs:
-  workflow_dispatch:
-    echo-hello:
+  echo-hello:
       runs-on: ubuntu-latest
       steps:
         - name: Say hello
           run: echo "Hello, World!"
-    echo-goodbye:
+  echo-goodbye:
       runs-on: ubuntu-latest
       steps: 
         - name: Failed step
-          run: ../imprime.sh
+          run: |
+            echo "I will fail"
+            exit 1
           continue-on-error: true
         - name: Say goodbye
           run: echo "Goodbye!"
-          
